apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-odoo-claim
  namespace: icgroup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 2Gi

