apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    env: prod
    app: odoo-web
  name: odoo-web
  namespace: icgroup
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
      app: odoo-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        env: prod
        app: odoo-web
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"        
      containers:
        - image: odoo:14
          name: odoo-web
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: odoo-postgres
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-pgsql-password
                  key: odoo
          volumeMounts:
            - name: odoo-persistent-storage
              mountPath: /var/lib/odoo
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"      
          readinessProbe:
            httpGet:
              path: /
              port: 8069
      volumes:
        - name: odoo-persistent-storage
          persistentVolumeClaim:
            claimName: data-odoo-claim
status: {}
