apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ic-webapp
      env: prod
  template:
    metadata:
      labels:
        app: ic-webapp
        env: prod
    spec:
      containers:
        - name: ic-webapp
          image: sh0t1m3/ic-webapp:1.0
          env:
            - name: ODOO_URL
              value: http://192.168.99.10:31000
            - name: PGADMIN_URL
              value: http://192.168.99.10:32000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources: {}
