# -*- mode: ruby -*-
# vi: set ft=ruby :
# To enable zsh, please set ENABLE_ZSH env var to "true" before launching vagrant up
#   + On windows => $env:ENABLE_ZSH="true"
#   + On Linux  => export ENABLE_ZSH="true

module OS
	def OS.windows?
		(/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
        end

        def OS.mac?
		(/darwin/ =~ RUBY_PLATFORM) != nil
	end
	def OS.unix?
		!OS.windows?
	end
	def OS.linux?
		OS.unix? and not OS.mac?
	end
end

Vagrant.configure("2") do |config|
  config.vm.define "icwebapp" do |icwebapp|
    icwebapp.vm.box = "geerlingguy/centos7"
    if OS.linux?
	icwebapp.vm.network "private_network",  type: "static", ip: "192.168.99.9", virtualbox__intnet: "08net"
    elsif OS.windows?
	icwebapp.vm.network "private_network",  type: "static", ip: "192.168.99.9"
    else
    	puts 'OS not managed'
    end

    icwebapp.vm.hostname = "icwebapp"
    icwebapp.vm.provider "virtualbox" do |v|
      v.name = "icwebapp"
      v.memory = 4096
      v.cpus = 2
    end
    icwebapp.vm.provision :shell do |shell|
      shell.path = "install_minikube.sh"
      shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end
    icwebapp.vm.provision :shell do |shell|
      shell.path = "install_longhorn.sh"
    end
    icwebapp.vm.provision :shell do |shell|
      shell.path = "install_app.sh"
    end
  end
end
